# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
remote_theme : alshedivat/al-folio
title: Jinu Jeong # the website title (if blank, full name will be used instead)


lang: en # the language of your site (for example: en, fr, cn, ru, etc.)
icon: ⚛️  # the emoji used as the favicon (alternatively, provide image name in /assets/img/)

url: jinu-jeong.github.io # the base hostname & protocol for your site


# Dimensions
max_width: 800px
